Vagrant.configure("2") do |config|
	config.vm.box = "debian/bookworm64"
	config.vm.hostname = "daw2-rosaca"
  
	config.vm.provider "virtualbox" do |v|
		v.name = "daw2-rosaca"
		v.memory = 2048
		v.cpus = 2
		v.customize ['modifyvm', :id, '--clipboard', 'bidirectional', '--groups', '/DAW2']     
	end
  
	config.vm.network "public_network"
         
	config.vm.synced_folder "/home/vadimvolkov/DAW2/M07/UF1/php/Projecte/src", "/var/www/html", owner: "www-data", group: "www-data"
    
	config.vm.provision "shell", inline: <<-SHELL
		sudo apt-get update -y
		sudo apt-get install -y aptitude
		sudo apt-get install -y net-tools
		sudo apt-get install -y git
		sudo apt-get install -y nano
		sudo apt-get install -y apache2 apache2-doc
		sudo apt-get install -y libapache2-mod-php
		sudo apt-get install -y php8.2
		sudo aptitude install -y php-xml composer
		sudo gpasswd -a vagrant www-data
		sudo chmod -R 770 /var/www/html		
		exit    
	SHELL

end
