IMATGE_BOX = "debian/bookworm64"
NOM_SISTEMA = "jenkins.fjeclot.net"
NOM_VM="m08uf4pr4"
MEMORIA = 2048
CPUS = 2
Vagrant.configure("2") do |config|
config.vm.box = IMATGE_BOX
config.vm.hostname = NOM_SISTEMA
config.vm.network "public_network"
config.vm.provider "virtualbox" do |v|
v.name = NOM_VM
v.memory = MEMORIA
v.cpus = CPUS
v.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
end
config.vm.provision "shell", inline: <<-SHELL
sudo apt-get update -y
sudo apt-get install -y net-tools
sudo apt-get install -y whois
sudo apt-get install -y aptitude
sudo apt-get install zip unzip
sudo apt-get install git
sudo apt-get -y install apt-transport-https ca-certificates curl gnupg2 software-properties-common
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
sudo apt-get update -y
sudo apt-get -y install docker-ce docker-ce-cli containerd.io docker-compose
sudo gpasswd -a vagrant docker
exit
SHELL
end
